name: RCPlayerMenu
main: de.raidcraft.playermenu.RCPlayerMenuPlugin
version: ${project.version}#${build.number}
author: Silthus
website: www.raid-craft.de
depend: [RaidCraft-API,RCSkills,RCSkillsHotbar,RCQuests]
database: true
api-version: 1.13